// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEjbytKoUc2thiliJvDrjpyEgd472mzEw',
    appId: '1:1030399222292:web:e79ca30287570767f4bd01',
    messagingSenderId: '1030399222292',
    projectId: 'soilgpt-cf913',
    authDomain: 'soilgpt-cf913.firebaseapp.com',
    storageBucket: 'soilgpt-cf913.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJaH8VQENI3pT8LbamrgzdXNaqucsb2h0',
    appId: '1:1030399222292:android:6f7578dbce18c0baf4bd01',
    messagingSenderId: '1030399222292',
    projectId: 'soilgpt-cf913',
    storageBucket: 'soilgpt-cf913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd6NWoI7rAexx8ud7wjcfmLhBFPhIfpXY',
    appId: '1:1030399222292:ios:60fda678de018a0ef4bd01',
    messagingSenderId: '1030399222292',
    projectId: 'soilgpt-cf913',
    storageBucket: 'soilgpt-cf913.firebasestorage.app',
    iosBundleId: 'com.example.soilgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd6NWoI7rAexx8ud7wjcfmLhBFPhIfpXY',
    appId: '1:1030399222292:ios:60fda678de018a0ef4bd01',
    messagingSenderId: '1030399222292',
    projectId: 'soilgpt-cf913',
    storageBucket: 'soilgpt-cf913.firebasestorage.app',
    iosBundleId: 'com.example.soilgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEjbytKoUc2thiliJvDrjpyEgd472mzEw',
    appId: '1:1030399222292:web:9b60eea1f97c9a58f4bd01',
    messagingSenderId: '1030399222292',
    projectId: 'soilgpt-cf913',
    authDomain: 'soilgpt-cf913.firebaseapp.com',
    storageBucket: 'soilgpt-cf913.firebasestorage.app',
  );
}
